
-- Crear Vista Reporte 
CREATE OR REPLACE VIEW VIW_REPORTE_EMPLEADOS AS
SELECT
    EMPRESA.IDEMPRESA AS intEmpresa,
    SUCURSALES.ID_SUCURSAL AS intSucursal,
    DEPARTAMENTO.IDDEPARTAMENTO AS intDepartamento,
    EMPLEADO.IDEMPLEADO AS intEmpleado,
    EMPRESA.NOMBRE AS strNomEmpresa, EMPLEADO.NOMBRE AS strNombreEmp, SUCURSALES.NOMBRE AS strSurNom, EMPLEADO.EDAD AS intEdadEmp, SUCURSALES.FECHA_APERTURA AS datFechApertura, DEPARTAMENTO.NOMBRE AS strDepNom
FROM EMPRESA
LEFT JOIN DEPARTAMENTO ON DEPARTAMENTO.IDEMPRESA = EMPRESA.IDEMPRESA 
LEFT JOIN SUCURSALES ON SUCURSALES.IDEMPRESA = EMPRESA.IDEMPRESA
LEFT JOIN EMPLEADO ON EMPLEADO.IDDEPARTAMENTO = DEPARTAMENTO.IDDEPARTAMENTO

WHERE EMPLEADO.EDAD = (SELECT MIN (EMPLEADO2.EDAD) 
                        FROM EMPLEADO EMPLEADO2 WHERE EMPLEADO2.IDDEPARTAMENTO = DEPARTAMENTO.IDDEPARTAMENTO)
AND SUCURSALES.FECHA_APERTURA = (SELECT MIN (SUCURSALES2.FECHA_APERTURA)
                                    FROM SUCURSALES SUCURSALES2 WHERE SUCURSALES2.IDEMPRESA = EMPRESA.IDEMPRESA)
ORDER BY EMPRESA.NOMBRE, DEPARTAMENTO.NOMBRE;
  
  SELECT * FROM VIW_REPORTE_EMPLEADOS;
                               

