-- Datos de la tabla EMPRESA
INSERT INTO EMPRESA (NOMBRE) VALUES ('Inube');
INSERT INTO EMPRESA (NOMBRE) VALUES ('TechNova');
INSERT INTO EMPRESA (NOMBRE) VALUES ('Soluciones SA');

-- Datos de la tabla DEPARTAMENTOS
-- Para Inube
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (5, 'Recursos Humanos');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (5, 'Desarrollo');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (5, 'Marketing');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (5, 'Finanzas');

-- Para TechNova
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (2, 'Desarrollo');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (2, 'Ventas');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (2, 'Atención al Cliente');

-- Para Soluciones SA
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (3, 'Operaciones');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (3, 'Administración');
INSERT INTO DEPARTAMENTO (IDEMPRESA, NOMBRE) VALUES (3, 'Soporte');


-- Datos para la tabla PUESTOS
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Gerente', 'Supervisa equipos y proyectos');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Analista', 'Analiza datos y reportes');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Desarrollador', 'Programa y mantiene sistemas');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Diseñador', 'Diseña materiales y UX');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Contador', 'Lleva la contabilidad y finanzas');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Recursos Humanos', 'Gestiona personal y nómina');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Soporte Técnico', 'Ayuda a resolver incidencias técnicas');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Marketing', 'Crea campañas y contenido');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Ventas', 'Vende productos y servicios');
INSERT INTO PUESTOS (NOMBRE, ACTIVIDADES) VALUES ('Operaciones', 'Coordina logística y procesos internos');

-- Datos para la tabla SUCURSALES
-- Inube
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (1, 'Sucursal Centro', 'Av. Reforma 123', 'Ciudad de México', TO_DATE('2015-03-15','YYYY-MM-DD'));
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (1, 'Sucursal Norte', 'Calle Norte 45', 'Monterrey', TO_DATE('2017-07-10','YYYY-MM-DD'));

-- TechNova
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (2, 'Sucursal Principal', 'Av. Tecnológica 78', 'Guadalajara', TO_DATE('2016-05-22','YYYY-MM-DD'));
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (2, 'Sucursal Sur', 'Calle Sur 12', 'Cancún', TO_DATE('2018-09-18','YYYY-MM-DD'));

-- Soluciones SA
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (3, 'Oficina Central', 'Av. Principal 1', 'Puebla', TO_DATE('2014-11-05','YYYY-MM-DD'));
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (3, 'Sucursal Este', 'Calle Este 33', 'Querétaro', TO_DATE('2019-01-20','YYYY-MM-DD'));
INSERT INTO SUCURSALES (IDEMPRESA, NOMBRE, DIRECCION, CIUDAD, FECHA_APERTURA) VALUES (3, 'Sucursal Oeste', 'Av. Oeste 44', 'Toluca', TO_DATE('2020-06-12','YYYY-MM-DD'));


-- Datos para la Tabla EMPLEADOS
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'María López', 30, TO_DATE('1993-05-12','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Carlos Pérez', 40, TO_DATE('1983-08-20','YYYY-MM-DD'), 10);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Ana García', 28, TO_DATE('1995-02-15','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Javier Ruiz', 35, TO_DATE('1988-12-01','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Sofía Martínez', 27, TO_DATE('1996-06-30','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Miguel Torres', 32, TO_DATE('1991-04-10','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Lucía Ramírez', 45, TO_DATE('1978-09-25','YYYY-MM-DD'), 25);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Patricia Gómez', 31, TO_DATE('1992-04-14','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Luis Mendoza', 37, TO_DATE('1986-09-30','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Carolina Silva', 29, TO_DATE('1994-12-05','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Jorge Medina', 41, TO_DATE('1982-07-21','YYYY-MM-DD'), 25);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Velkan Valerius', 28, TO_DATE('2001-08-23','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'empleado de prueba', 25, TO_DATE('2002-12-24','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'empleado ultimo', 29, TO_DATE('2012-06-19','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Darío Simón', 23, TO_DATE('2002-03-11','YYYY-MM-DD'), 10);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Santiago López', 34, TO_DATE('1989-03-12','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Valentina Torres', 29, TO_DATE('1994-11-05','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Mateo García', 31, TO_DATE('1992-07-21','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Isabela Ramírez', 26, TO_DATE('1997-02-14','YYYY-MM-DD'), 25);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Emiliano Pérez', 38, TO_DATE('1985-08-30','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Camila Fernández', 27, TO_DATE('1996-05-10','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Lucas Sánchez', 33, TO_DATE('1990-12-01','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Valeria Ortiz', 30, TO_DATE('1993-06-25','YYYY-MM-DD'), 25);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Diego Morales', 28, TO_DATE('1995-09-17','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Lucía Herrera', 32, TO_DATE('1991-01-09','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Gabriel Ruiz', 35, TO_DATE('1988-04-22','YYYY-MM-DD'), 24);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (4, 'Mariana Castillo', 29, TO_DATE('1994-10-15','YYYY-MM-DD'), 25);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (1, 'Sebastián Gómez', 31, TO_DATE('1992-03-05','YYYY-MM-DD'), 11);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (2, 'Paula Díaz', 28, TO_DATE('1995-08-20','YYYY-MM-DD'), 23);
INSERT INTO EMPLEADO (IDDEPARTAMENTO, NOMBRE, EDAD, FECHANACIMIENTO, ID_PUESTO) VALUES (3, 'Andrés Romero', 36, TO_DATE('1987-11-11','YYYY-MM-DD'), 24);

COMMIT;



